Repository palantir/palantir-python-sdk, pull requests merged in 2022-04, with the labels that each got.

#3 Fix user agent
  palantir/core/rpc.py
Labels: merge when ready, no changelog

#4 Update README
  README.md
Labels: no changelog

#5 Update dependencies
  palantir/datasets/rpc/catalog.py
  palantir/datasets/rpc/data_proxy.py
  palantir/datasets/rpc/path.py
  palantir/datasets/rpc/schema.py
  palantir/datasets/rpc/sql.py
  poetry.lock
  pyproject.toml
Labels: no changelog

#6 Allow uploading a file to an open transaction
  palantir/datasets/core.py
Labels: merge when ready, no changelog, autorelease

#7 Add badges to README
  README.md
Labels: no changelog

#8 Fix TypeError when deserializing a Transaction
  palantir/datasets/rpc/catalog.py
Labels: merge when ready, no changelog, autorelease

#11 Read dataset with the end transaction RID
  changelog/@unreleased/pr-11.v2.yml
  palantir/datasets/client.py
  test/datasets/test_client.py
Labels: merge when ready, autorelease

#13 Fix environment variable names
  README.md
Labels: merge when ready, no changelog

#12 Add additional package metadata
  pyproject.toml
Labels: merge when ready, no changelog, autorelease

#14 Add branch ID to the read dataset query
  changelog/@unreleased/pr-14.v2.yml
  palantir/datasets/client.py
  test/datasets/test_client.py
Labels: merge when ready, autorelease

#16 Remove unnecessary quotes separating transaction and branch
  changelog/@unreleased/pr-16.v2.yml
  palantir/datasets/client.py
  test/datasets/test_client.py
Labels: merge when ready, autorelease

#17 Update readme
  README.md
Labels: merge when ready, no changelog
